app_default_index:
    path:     /
    defaults: { _controller: AppBundle:Default:index }
    methods:  GET

app_product_index:
    path:     /products
    defaults: { _controller: AppBundle:Product:index }
    methods:  GET

app_product_show:
    path:     /product/{id}
    defaults: { _controller: AppBundle:Product:show }
    methods:  GET
